### ISSUE TITLE
CRITICAL: Scania can move while platform is raised

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#15]
I can call `startEngine()` on Scania while its platform is raised, making it accelerate a tiny bit. Then when I call `move()` it will move, even though the platform is raised.
https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/src/Vehicle.java#L77

**Comment by chrille0313** [comment]
@martinjonsson01: Are we allowed to change the code that was given in the first assignment? Or are we supposed to work around this and find another solution? Because we have agreed that we don't really like how the speed is currently implemented. It doesn't make sense that the car just stops when you turn off the engine for example.

**Comment by martinjonsson01** [comment]
Sure, you're free to modify how the starting/stopping of the engine works, if you'd like. Keep in mind, though, that whenever you make any changes to the public-facing API then you might be breaking code that depends on it (like the code from lab 3), so if you can, try to do it without changing the public API. 

But if the only reason you want to change this is because it doesn't make sense, then I'd suggest you do it later and instead prioritize completing the tasks in the labs and the written assignment. Since what we want you to focus on are the design problems, not the specific implementation details of a feature like the engine.

**Comment by Zazmuz** [comment]
We changed how start and stop engine operates which in turn made this issue go away, the issue arised from start engine setting the current speed to 0.1?! Instead of doing whats expected which is allowing us to increase our speed by pressing down the gas pedal. Basically it started moving automatically by starting the motor which did not have a check.

We now changed it so that by turning on/off the engine it toggles a boolean which allows/disallows us to increase our speed / use our engine.
